export const KEYS_MAP: { [key: string]: string } = {
  AC: 'Backspace',
  DEL: 'Delete',
  '/': '/',
  '7': '7',
  '8': '8',
  '9': '9',
  X: '*',
  '4': '4',
  '5': '5',
  '6': '6',
  '-': '-',
  '1': '1',
  '2': '2',
  '3': '3',
  '+': '+',
  '0': '0',
  '.': '.',
  '=': 'Enter',
} as const
